const photo={'멸치':'https://ecimg.cafe24img.com/pg298b50889312068/withtaste/web/product/extra/big/20230406/84b43dea366f887c14955c49d111830d.jpg','붕장어':'assets/fish/conger-nifs.jpg','먹장어':'assets/fish/hagfish.jpg','오징어':'https://commons.wikimedia.org/wiki/Special:FilePath/Todarodes%20pacificus.jpg?width=800','도다리':'https://commons.wikimedia.org/wiki/Special:FilePath/Paralichthys%20olivaceus.jpg?width=800','가자미':'https://commons.wikimedia.org/wiki/Special:FilePath/Paralichthys%20olivaceus.jpg?width=800','볼락':'https://commons.wikimedia.org/wiki/Special:FilePath/Sebastes%20schlegelii.jpg?width=800','전갱이':'assets/fish/horse-mackerel-nifs.jpg','고등어':'https://m.luckyfull.com/web/product/big/201806/104_shop1_15293914933265.jpg','갈치':'assets/fish/galchi-nifs.jpg','숭어':'https://commons.wikimedia.org/wiki/Special:FilePath/Mugil%20cephalus.jpg?width=800','전어':'assets/fish/jeoneo-nifs.jpg','농어':'assets/fish/seabass-nifs.jpg'};
const seed=[['기장','멸치',[3,4,5,6],9000,22,'멸치회 · 찌개 · 구이'],['기장','붕장어',[1,2,3,4,5,6,7,8,9,10,11,12],21000,18,'소금구이 · 장어탕 · 회'],['기장','먹장어',[6,7,8,9],18000,16,'소금구이 · 양념구이 · 매운탕'],['기장','오징어',[6,7,8,9,10,11],15000,20,'회 · 버터구이 · 물회'],['송정','도다리',[2,3,4],19000,13,'쑥국 · 회 · 구이'],['송정','가자미',[10,11,12,1,2,3],16000,12,'구이 · 찜 · 조림'],['송정','볼락',[12,1,2,3,4],22000,9,'매운탕 · 구이 · 조림'],['송정','전갱이',[6,7,8,9,10],12000,23,'소금구이 · 회 · 조림'],['영도','고등어',[9,10,11],14000,17,'고등어구이 · 조림 · 회'],['영도','전갱이',[6,7,8,9,10],12000,15,'소금구이 · 회 · 조림'],['영도','갈치',[8,9,10,11],26000,11,'갈치구이 · 조림 · 구이'],['영도','볼락',[12,1,2,3,4],22000,8,'매운탕 · 구이 · 조림'],['다대포','숭어',[10,11,12,1,2],16000,19,'숭어회 · 매운탕 · 구이'],['다대포','전어',[8,9,10],15000,25,'전어회 · 구이 · 무침'],['다대포','농어',[5,6,7,8,9,10],28000,7,'농어회 · 소금구이 · 맑은탕'],['다대포','도다리',[2,3,4],19000,10,'쑥국 · 회 · 구이']];
const baseFish=seed.map(([area,name,months,price,qty,recipes],i)=>({id:`base-${i}`,area,name,months,price:Math.round(price/2),qty,recipes,emoji:['🐟','🐠','🦑'][i%3],time:`0${6+i%3}:2${i%6}`,image:photo[name],phone:'010-2458-7721',seller:'부산 바다어부',base:true}));
const STORE='eobusan-v3',today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date()),$=s=>document.querySelector(s);
let state=loadState(),fish=[];let selectedMonth=new Date().getMonth()+1;
function loadState(){try{const value=JSON.parse(localStorage.getItem(STORE));return value&&typeof value==='object'?value:{}}catch{return{}}}
function saveState(){localStorage.setItem(STORE,JSON.stringify(state))}
function hydrate(){if(state.drawResetVersion!=='draw-opportunity-restore-1'){state.drawResetVersion='draw-opportunity-restore-1';state.drawDate=today;state.dailyDraws=0;saveState()}else if(state.drawDate!==today){state.drawDate=today;state.dailyDraws=0;state.lastDraw=null;saveState()}fish=[...baseFish.map(f=>({...f})),...(state.sellerFish||[])];}
hydrate();
const available=()=>fish.filter(f=>f.months.includes(selectedMonth)),fishAt=i=>fish[i];
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='rescue')renderRescue();if(id==='my')renderMy();if(id==='draw')resetDraw();if(id==='map')setTimeout(initBusanMap,80)}
function image(f,cls=''){return `<img class="${cls}" src="${f.image}" alt="${f.area} ${f.name}" onerror="this.style.display='none';this.parentElement.classList.add('image-fallback')">`}
function indexOfId(id){return fish.findIndex(f=>f.id===id)}
function renderDrawLimit(){const label=$('#draw-count');if(label)label.textContent=`🎣 오늘 2회 가능 · 남은 뽑기 ${Math.max(0,2-(state.dailyDraws||0))}회`}
function drawMarkup(f){return `<div class="draw-result">${image(f,'result-photo')}<div class="discount">오늘의 바다뽑기 · 5% 할인</div><h2>🎉 ${f.area} ${f.name} 당첨!</h2><p>📍 ${f.area} 앞바다 · 오늘 ${f.time} 어획<br>남은 수량 ${f.qty}마리</p><button class="primary" onclick="openFish('${f.id}',true)">5% 할인 받고 데려가기</button></div>`}
function resetDraw(){const card=$('#draw-card');card.classList.remove('result-ready');card.innerHTML='<div class="draw-wave">🌊</div><div class="mystery">?</div>';renderDrawLimit();renderSavedDraws()}
function weightedPick(){const current=available(),pool=current.flatMap(f=>Array(Math.max(1,f.qty)).fill(f));return pool[Math.floor(Math.random()*pool.length)]}
function drawFish(){if((state.dailyDraws||0)>=2)return toast('오늘의 바다뽑기 2회를 모두 사용했어요. 내일 다시 만나요!');if(!available().length)return toast('오늘 어획 가능 어종이 없어요.');state.dailyDraws=(state.dailyDraws||0)+1;const f=weightedPick(),saved={id:f.id,fish:{...f},date:today,time:new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})};state.lastDraw=saved;state.drawHistory=[saved,...(state.drawHistory||[])].slice(0,8);saveState();renderDrawLimit();const card=$('#draw-card');card.classList.remove('result-ready');card.innerHTML='<div class="mystery">🎣</div><p>부산 바다에서 수산물을 찾는 중...</p>';setTimeout(()=>{const latest=fish.find(x=>x.id===f.id)||f;card.classList.add('result-ready');card.innerHTML=drawMarkup(latest);renderSavedDraws()},600)}
function renderSavedDraws(){const target=$('#draw-saved-list');if(!target)return;const items=state.drawHistory||[];target.innerHTML=items.length?items.map(item=>{const f=fish.find(x=>x.id===item.id)||item.fish;return `<article class="saved-draw"><div>${image(f,'saved-draw-photo')}</div><span><small>${item.date===today?'오늘 '+item.time:item.date}</small><b>${f.area} ${f.name} 당첨</b><em>바다뽑기 5% 할인</em></span><button type="button" onclick="openFish('${f.id}',true)">보기</button></article>`}).join(''):'<p class="empty small-empty">아직 저장된 뽑기 결과가 없어요.</p>'}
function marketOptions(f){return fish.filter(x=>x.name===f.name&&x.qty>0).sort((a,b)=>a.price-b.price)}
function openFish(id,drawDiscount=false){const i=typeof id==='number'?id:indexOfId(id),f=fishAt(i);if(!f)return;const offers=marketOptions(f),low=offers[0]?.price||f.price,high=offers[offers.length-1]?.price||f.price;$('#modal-content').innerHTML=`<div class="draw-result">${image(f,'result-photo')}<h2>${f.area} ${f.name}</h2><div class="market-box"><b>📊 ${f.name} 오늘의 시세</b><strong>${low.toLocaleString()} ~ ${high.toLocaleString()}원 <small>/ 1마리</small></strong><p>같은 어종 ${offers.length}개 판매자 상품을 비교했어요.</p></div><div class="seller-offers">${offers.map(o=>`<button type="button" class="seller-offer ${o.id===f.id?'selected':''}" onclick="openFish('${o.id}',${drawDiscount})"><span>${image(o,'offer-photo')}</span><b>${o.seller}</b><small>${o.area} · ${o.qty}마리</small><strong>${o.price.toLocaleString()}원</strong></button>`).join('')}</div><p>📍 ${f.area} 앞바다 · 오늘 ${f.time} 어획<br>남은 수량 <b>${f.qty}마리</b><br>추천 메뉴: ${f.recipes}</p><label class="quantity-label">구매 마리 수 <input id="buy-qty" type="number" min="1" max="${f.qty}" value="1" oninput="updatePurchaseTotal('${f.id}',${drawDiscount})"></label><div id="purchase-total" class="purchase-total"></div><label class="offer-label">적정 가격 제안 (1마리)<input id="price-offer" type="number" placeholder="원하는 가격 입력"><button type="button" onclick="submitOffer('${f.id}')">가격 제안하기</button></label><button type="button" class="primary purchase-button" onclick="reserve('${f.id}',${drawDiscount})">판매자와 픽업 확인하기</button></div>`;$('#modal').classList.remove('hidden');updatePurchaseTotal(f.id,drawDiscount)}
function updatePurchaseTotal(id,discount){const f=fish.find(x=>x.id===id),qty=Math.max(1,Math.min(f.qty,Number($('#buy-qty').value)||1));$('#buy-qty').value=qty;const unit=Math.round(f.price*(discount?.95:1)),total=unit*qty;$('#purchase-total').innerHTML=`${discount?'바다뽑기 5% 할인 적용 · ':''}<b>${qty}마리 · 총 ${total.toLocaleString()}원</b>`}
function submitOffer(id){const f=fish.find(x=>x.id===id),amount=Number($('#price-offer').value);if(!amount)return toast('제안할 가격을 입력해주세요.');state.offers=[...(state.offers||[]),{id,amount,date:new Date().toLocaleDateString('ko-KR')}];saveState();toast(`${f.name} ${amount.toLocaleString()}원 제안을 판매자에게 보냈어요!`)}
function closeModal(){$('#modal').classList.add('hidden')}
function reserve(id,discount){const f=fish.find(x=>x.id===id),qty=Math.max(1,Math.min(f.qty,Number($('#buy-qty').value)||1)),unit=Math.round(f.price*(discount?.95:1)),amount=unit*qty;if(!f.qty)return toast('준비된 수량이 모두 예약되었어요.');$('#modal-content').innerHTML=`<div class="draw-result"><div class="big">📍</div><h2>판매자와 픽업 확인</h2><p><b>${f.area} ${f.name} ${qty}마리</b> 예약 전, 판매자와 수령 정보를 확인해주세요.</p><div class="pickup-card"><b>📍 픽업 위치</b>${f.area} 수산물 직거래장<br>오늘 16:00 ~ 19:00 수령 가능<br><br><b>👨‍🌾 판매자 연락</b>${f.seller} · ${f.phone}<div class="contact-actions"><a href="tel:${f.phone.replaceAll('-','')}">📞 전화하기</a><a href="sms:${f.phone.replaceAll('-','')}">💬 문자 보내기</a></div></div><button type="button" class="primary purchase-button" onclick="showPayment('${id}',${qty},${amount})">픽업 확인 후 결제하기</button></div>`}
function showPayment(id,qty,amount){const f=fish.find(x=>x.id===id);$('#modal-content').innerHTML=`<div class="draw-result"><div class="big">💳</div><h2>가상 결제</h2><p><b>${f.area} ${f.name} ${qty}마리</b><br>결제 금액 <b>${amount.toLocaleString()}원</b></p><label class="payment-option"><input type="radio" name="pay" checked><span><b>카카오페이</b><small>테스트 결제 · 실제 청구되지 않아요</small></span></label><label class="payment-option"><input type="radio" name="pay"><span><b>신용·체크카드</b><small>테스트 결제 · 실제 청구되지 않아요</small></span></label><button type="button" class="primary purchase-button" onclick="completePayment('${id}',${qty},${amount})">${amount.toLocaleString()}원 결제하기</button></div>`}
function completePayment(id,qty,amount){const f=fish.find(x=>x.id===id);f.qty-=qty;const custom=(state.sellerFish||[]).find(x=>x.id===id);if(custom)custom.qty=f.qty;state.rescued=(state.rescued||0)+qty;state.found=[...new Set([...(state.found||[]),f.name])];state.purchases=[{id:crypto.randomUUID?.()||Date.now().toString(),name:f.name,area:f.area,seller:f.seller,qty,amount,date:new Date().toLocaleDateString('ko-KR'),image:f.image},...(state.purchases||[])];saveState();render();$('#modal-content').innerHTML=`<div class="draw-result"><div class="big">🎉</div><h2>결제가 완료됐어요!</h2><p><b>${f.area} ${f.name} ${qty}마리</b> 구조에 참여해주셔서 감사합니다.<br>MY 화면의 구매 내역과 도감에서 확인할 수 있어요.</p><button class="primary" onclick="closeModal()">확인</button></div>`}
function renderRescue(){$('#rescue-list').innerHTML=[...available()].sort((a,b)=>b.qty-a.qty).map(f=>`<article class="rescue"><div class="rescue-head"><b>${f.emoji} ${f.area} ${f.name}</b><strong>${f.qty}마리 남음</strong></div><p>${f.seller} 판매 상품 · ${f.price.toLocaleString()}원/마리</p><div class="progress"><i style="width:${Math.min(100,(1-f.qty/31)*100)}%"></i></div><button onclick="openFish('${f.id}')">${f.name} 시세 보고 구조하기</button></article>`).join('')||'<p class="empty">이번 달 구조 요청이 없어요.</p>'}
function renderPurchaseHistory(all=false){const target=$('#purchase-history'),items=state.purchases||[];target.innerHTML=items.length?items.slice(0,all?items.length:2).map(p=>`<article class="history-item"><span>${p.image?`<img src="${p.image}" alt="${p.name}">`:'🐟'}</span><div><b>${p.name} ${p.qty}마리</b><small>${p.area} · ${p.seller} · ${p.date}</small></div><strong>${p.amount.toLocaleString()}원</strong></article>`).join(''):'<p class="empty small-empty">아직 구매 내역이 없어요.<br>바다 친구를 구조해보세요!</p>'}
function renderMy(){const rescued=state.rescued||0,found=state.found||[],level=Math.max(1,Math.floor(rescued/3)+1),rewards=[[10,'🌊','바다 플로팅 키링'],[25,'🎟️','다음 픽업 10% 쿠폰'],[50,'🧊','보냉백 굿즈'],[100,'👑','바다 수호자 한정 배지']];$('#rescued-count').textContent=rescued;$('#found-count').textContent=found.length;$('#level').textContent=level;$('#level-copy').textContent=`구조 ${rescued}마리 · 다음 등급까지 ${Math.max(0,level*3-rescued)}마리 남았어요.`;$('#reward-list').innerHTML=rewards.map(([count,icon,title])=>`<div class="reward-row ${rescued>=count?'unlocked':''}"><i>${icon}</i><span><b>${count}마리 구조 · ${title}</b><small>${rescued>=count?'획득 완료!':'앞으로 '+Math.max(0,count-rescued)+'마리 더 구조해요'}</small></span></div>`).join('');$('#dex-progress').textContent=`${found.length} / ${new Set(fish.map(f=>f.name)).size}`;$('#collection').innerHTML=[...new Map(fish.map(f=>[f.name,f])).values()].map(f=>`<div class="dex-card ${found.includes(f.name)?'found':''}"><span>${found.includes(f.name)?image(f):'?'}</span><b>${found.includes(f.name)?f.name:'???'}</b><small>${found.includes(f.name)?'도감 등록 완료':'미발견 생물'}</small></div>`).join('');renderPurchaseHistory()}
function filterArea(area){const choices=available().filter(f=>f.area===area);$('#area-result').innerHTML=`<b>📍 ${area} 앞바다 · 오늘 입고</b><br>${choices.map(f=>`${f.emoji} ${f.name} · ${f.qty}마리`).join('<br>')||'오늘 등록된 수산물이 없어요.'}`}
function readImage(file){return new Promise(resolve=>{if(!file)return resolve('');const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file)})}
$('#seller-form').addEventListener('submit',async e=>{e.preventDefault();const name=$('#new-name').value.trim(),area=$('#new-area').value,qty=Number($('#new-qty').value),image=await readImage($('#new-photo').files[0]);const product={id:`seller-${Date.now()}`,name,area,time:$('#new-time').value,price:Number($('#new-price').value),qty,emoji:'🐟',recipes:'구이 · 회 · 조림',image:image||photo[name]||'',phone:$('#seller-phone').value.trim()||'010-2458-7721',seller:$('#seller-name').value.trim(),months:[selectedMonth],sellerPhoto:!!image};state.sellerFish=[product,...(state.sellerFish||[])];saveState();hydrate();e.target.reset();go('home');render();toast(`${name} ${qty}마리가 ${name} 카테고리에 등록됐어요!`)});
function render(){const current=available(),total=current.reduce((a,f)=>a+f.qty,0),areas=['기장','송정','영도','다대포'];$('#total-count').textContent=total;$('#season-insight').innerHTML=`오늘 입고된 부산 4개 권역의 <b>${current.length}개 판매 상품</b>을 만나보세요.`;const urgent=[...current].sort((a,b)=>b.qty-a.qty)[0];$('#urgent-card').innerHTML=urgent?`<div class="urgent-top"><span>🚨 바다 구조 요청!</span><span>${urgent.qty}마리 남음</span></div><b>${urgent.area} ${urgent.name}</b><p>${urgent.seller}의 오늘 입고 상품이에요.<br>시세를 비교하고 적정 가격을 제안해보세요!</p><div class="progress"><i style="width:${Math.min(100,(1-urgent.qty/31)*100)}%"></i></div><small>구조 진행 중</small>`:'<b>오늘 등록된 어종이 없어요.</b>';$('#fish-list').innerHTML=areas.map(area=>{const items=current.filter(f=>f.area===area);return `<section class="region-block"><div class="region-head"><h3>📍 ${area} 앞바다</h3><small>${items.length}개 상품 입고</small></div><div class="region-fish-grid">${items.map(f=>{const options=marketOptions(f),low=options[0]?.price||f.price;return `<article class="fish" onclick="openFish('${f.id}')"><div class="fish-photo">${image(f)}</div><b>${f.name}</b><small>${f.seller}${f.sellerPhoto?' · 판매자 사진':''}</small><small>${f.time} 어획 · ${f.qty}마리</small><strong>${low.toLocaleString()}원~</strong><em>📊 ${options.length}곳 시세 비교</em></article>`}).join('')||'<p class="empty">오늘 등록된 수산물이 없어요.</p>'}</div></section>`}).join('')}
let busanMap;function initBusanMap(){if(!window.L)return;if(busanMap){busanMap.invalidateSize();return}busanMap=L.map('busan-real-map',{zoomControl:false,scrollWheelZoom:false}).setView([35.155,129.103],10);L.control.zoom({position:'bottomright'}).addTo(busanMap);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap contributors'}).addTo(busanMap);const points={기장:[35.244,129.215,'기장 대변항'],송정:[35.180,129.203,'송정해수욕장'],영도:[35.083,129.070,'영도 남항'],다대포:[35.048,128.966,'다대포항']};Object.entries(points).forEach(([area,[lat,lng,label]])=>{const marker=L.circleMarker([lat,lng],{radius:9,color:'#fff',weight:3,fillColor:'#ef6755',fillOpacity:1}).addTo(busanMap);marker.bindTooltip(`${area} 어획 포인트`,{direction:'top',offset:[0,-10]});marker.on('click',()=>{filterArea(area);const items=available().filter(f=>f.area===area);marker.bindPopup(`<b>📍 ${label}</b><br>${items.map(f=>`${f.emoji} ${f.name} · ${f.qty}마리`).join('<br>')||'오늘 등록된 수산물이 없어요.'}`).openPopup()})})}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}
render();renderMy();
