const photo={'멸치':'https://ecimg.cafe24img.com/pg298b50889312068/withtaste/web/product/extra/big/20230406/84b43dea366f887c14955c49d111830d.jpg','붕장어':'assets/fish/conger-nifs.jpg','먹장어':'assets/fish/hagfish.jpg','오징어':'https://commons.wikimedia.org/wiki/Special:FilePath/Todarodes%20pacificus.jpg?width=800','도다리':'https://commons.wikimedia.org/wiki/Special:FilePath/Paralichthys%20olivaceus.jpg?width=800','가자미':'https://commons.wikimedia.org/wiki/Special:FilePath/Paralichthys%20olivaceus.jpg?width=800','볼락':'https://commons.wikimedia.org/wiki/Special:FilePath/Sebastes%20schlegelii.jpg?width=800','전갱이':'assets/fish/horse-mackerel-nifs.jpg','고등어':'https://m.luckyfull.com/web/product/big/201806/104_shop1_15293914933265.jpg','갈치':'assets/fish/galchi-nifs.jpg','숭어':'https://commons.wikimedia.org/wiki/Special:FilePath/Mugil%20cephalus.jpg?width=800','전어':'assets/fish/jeoneo-nifs.jpg','농어':'assets/fish/seabass-nifs.jpg'};
const seed=[['기장','멸치',[3,4,5,6],9000,22,'멸치회 · 찌개 · 구이'],['기장','붕장어',[1,2,3,4,5,6,7,8,9,10,11,12],21000,18,'소금구이 · 장어탕 · 회'],['기장','먹장어',[6,7,8,9],18000,16,'소금구이 · 양념구이 · 매운탕'],['기장','오징어',[6,7,8,9,10,11],15000,20,'회 · 버터구이 · 물회'],['송정','도다리',[2,3,4],19000,13,'쑥국 · 회 · 구이'],['송정','가자미',[10,11,12,1,2,3],16000,12,'구이 · 찜 · 조림'],['송정','볼락',[12,1,2,3,4],22000,9,'매운탕 · 구이 · 조림'],['송정','전갱이',[6,7,8,9,10],12000,23,'소금구이 · 회 · 조림'],['영도','고등어',[9,10,11],14000,17,'고등어구이 · 조림 · 회'],['영도','전갱이',[6,7,8,9,10],12000,15,'소금구이 · 회 · 조림'],['영도','갈치',[8,9,10,11],26000,11,'갈치구이 · 조림 · 구이'],['영도','볼락',[12,1,2,3,4],22000,8,'매운탕 · 구이 · 조림'],['다대포','숭어',[10,11,12,1,2],16000,19,'숭어회 · 매운탕 · 구이'],['다대포','전어',[8,9,10],15000,25,'전어회 · 구이 · 무침'],['다대포','농어',[5,6,7,8,9,10],28000,7,'농어회 · 소금구이 · 맑은탕'],['다대포','도다리',[2,3,4],19000,10,'쑥국 · 회 · 구이']];
const baseFish=seed.map(([area,name,months,price,qty,recipes],i)=>({id:`base-${i}`,area,name,months,price:Math.round(price/2),qty,recipes,emoji:['🐟','🐠','🦑'][i%3],time:`0${6+i%3}:2${i%6}`,image:photo[name],phone:'010-2458-7721',seller:'부산 바다어부',base:true}));
const STORE='eobusan-v3',today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date()),$=s=>document.querySelector(s);
let state=loadState(),fish=[];let selectedMonth=new Date().getMonth()+1;
const SEA_POINTS={기장:{lat:35.244,lng:129.215,label:'기장 대변항',description:'동해의 맑고 깊은 물이 만나는 곳으로 멸치와 붕장어, 오징어 어획이 활발해요.',specialty:'멸치 · 붕장어 · 오징어'},송정:{lat:35.180,lng:129.203,label:'송정 앞바다',description:'잔잔한 연안과 암초 지대가 이어져 도다리와 가자미, 전갱이를 만나기 좋아요.',specialty:'도다리 · 가자미 · 전갱이'},영도:{lat:35.083,lng:129.070,label:'영도 남항',description:'부산항과 가까운 깊은 바다의 길목으로 고등어와 갈치, 볼락이 들어와요.',specialty:'고등어 · 갈치 · 볼락'},다대포:{lat:35.048,lng:128.966,label:'다대포 앞바다',description:'낙동강과 남해가 만나는 풍부한 어장으로 전어와 숭어, 농어가 유명해요.',specialty:'전어 · 숭어 · 농어'}};
function loadState(){try{const value=JSON.parse(localStorage.getItem(STORE));return value&&typeof value==='object'?value:{}}catch{return{}}}
function saveState(){localStorage.setItem(STORE,JSON.stringify(state))}
function hydrate(){const isNewMarketDay=state.marketDate&&state.marketDate!==today;if(isNewMarketDay){const soldIds=Object.keys(state.soldOut||{});state.expiredFishIds=[...new Set([...(state.expiredFishIds||[]),...soldIds])];state.sellerFish=(state.sellerFish||[]).filter(f=>!soldIds.includes(f.id));state.stock={};state.soldOut={}}state.marketDate=today;if(state.drawResetVersion!=='draw-opportunity-restore-1'){state.drawResetVersion='draw-opportunity-restore-1';state.drawDate=today;state.dailyDraws=0}else if(state.drawDate!==today){state.drawDate=today;state.dailyDraws=0;state.lastDraw=null}fish=[...baseFish.filter(f=>!(state.expiredFishIds||[]).includes(f.id)).map(f=>({...f,...(state.stock?.[f.id]!==undefined?{qty:state.stock[f.id]}:{})})),...(state.sellerFish||[])];saveState();}
hydrate();
const available=()=>fish.filter(f=>f.months.includes(selectedMonth)),fishAt=i=>fish[i];
function playTone(kind='tap'){try{const AudioCtx=window.AudioContext||window.webkitAudioContext,ctx=new AudioCtx(),osc=ctx.createOscillator(),gain=ctx.createGain();const tones={tap:[440,.05],spin:[660,.18],win:[880,.28],level:[1046,.25]};const [freq,duration]=tones[kind]||tones.tap;osc.frequency.setValueAtTime(freq,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*1.5,ctx.currentTime+duration);gain.gain.setValueAtTime(.07,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+duration)}catch{}}
function showOdds(){const pool=available(),total=pool.reduce((sum,f)=>sum+Math.max(1,f.qty),0);$('#modal-content').innerHTML=`<div class="odds-modal"><div class="big">🎲</div><h2>오늘의 등장 확률</h2><p>남은 수량이 많을수록 등장할 가능성이 높아요.</p><div class="odds-list">${pool.sort((a,b)=>b.qty-a.qty).map(f=>`<div><span>${f.emoji} ${f.area} ${f.name}</span><b>${(Math.max(1,f.qty)/total*100).toFixed(1)}%</b></div>`).join('')}</div><button class="primary" onclick="closeModal()">확인</button></div>`;$('#modal').classList.remove('hidden')}
function levelInfo(rescued){let level=1,spent=0;while(rescued>=spent+(level+2)){spent+=level+2;level++}const need=level+2,progress=rescued-spent;return{level,need,progress,toNext:need-progress,pct:progress/need*100}}
function claimMission(key,reward){state.claimedMissions=state.claimedMissions||[];if(state.claimedMissions.includes(key))return;state.claimedMissions.push(key);state.mileage=(state.mileage||0)+reward;saveState();renderMy();playTone('win');toast(`🪙 마일리지 ${reward}M을 받았어요!`)}
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='rescue')renderRescue();if(id==='my')renderMy();if(id==='draw')resetDraw();if(id==='map')setTimeout(initBusanMap,80)}
function image(f,cls=''){return `<img class="${cls}" src="${f.image}" alt="${f.area} ${f.name}" onerror="this.style.display='none';this.parentElement.classList.add('image-fallback')">`}
function indexOfId(id){return fish.findIndex(f=>f.id===id)}
function handleFishClick(id){const f=fish.find(x=>x.id===id);if(!f?.qty)return toast('오늘 판매가 완료된 상품이에요. 내일 목록에서 사라져요.');openFish(id)}
function renderDrawLimit(){const label=$('#draw-count');if(label)label.textContent=`🎣 오늘 2회 가능 · 남은 뽑기 ${Math.max(0,2-(state.dailyDraws||0))}회`}
function drawMarkup(f){return `<div class="draw-result">${image(f,'result-photo')}<div class="discount">오늘의 바다뽑기 · 5% 할인</div><h2>🎉 ${f.area} ${f.name} 당첨!</h2><p>📍 ${f.area} 앞바다 · 오늘 ${f.time} 어획<br>남은 수량 ${f.qty}마리</p><button class="primary" onclick="openFish('${f.id}',true)">5% 할인 받고 데려가기</button></div>`}
function resetDraw(){const card=$('#draw-card');card.classList.remove('result-ready');card.innerHTML='<div class="draw-wave">🌊</div><div class="mystery">?</div>';renderDrawLimit();renderSavedDraws()}
function weightedPick(){const current=available(),pool=current.flatMap(f=>Array(Math.max(1,f.qty)).fill(f));return pool[Math.floor(Math.random()*pool.length)]}
function drawFish(){if((state.dailyDraws||0)>=2)return toast('오늘의 바다뽑기 2회를 모두 사용했어요. 내일 다시 만나요!');if(!available().length)return toast('오늘 어획 가능 어종이 없어요.');playTone('spin');state.dailyDraws=(state.dailyDraws||0)+1;const f=weightedPick(),saved={id:f.id,fish:{...f},date:today,time:new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'})};state.lastDraw=saved;state.drawHistory=[saved,...(state.drawHistory||[])].slice(0,8);state.dexLevels=state.dexLevels||{};state.dexLevels[f.name]=(state.dexLevels[f.name]||0)+1;state.found=[...new Set([...(state.found||[]),f.name])];saveState();renderDrawLimit();const card=$('#draw-card');card.classList.remove('result-ready');card.classList.add('is-drawing');card.innerHTML='<div class="draw-game-ui"><span>CASTING...</span><i>✦</i><i>✦</i></div><div class="mystery">🎣</div><p>부산 바다에서 수산물을 찾는 중...</p>';setTimeout(()=>{const latest=fish.find(x=>x.id===f.id)||f;card.classList.remove('is-drawing');card.classList.add('result-ready');card.innerHTML=drawMarkup(latest);renderSavedDraws();renderMy();playTone(state.dexLevels[f.name]>1?'level':'win');toast(`${f.name} 도감 Lv.${state.dexLevels[f.name]} 달성!`)},900)}
function renderSavedDraws(){const target=$('#draw-saved-list');if(!target)return;const items=state.drawHistory||[];target.innerHTML=items.length?items.map(item=>{const f=fish.find(x=>x.id===item.id)||item.fish;return `<article class="saved-draw"><div>${image(f,'saved-draw-photo')}</div><span><small>${item.date===today?'오늘 '+item.time:item.date}</small><b>${f.area} ${f.name} 당첨</b><em>바다뽑기 5% 할인</em></span><button type="button" onclick="openFish('${f.id}',true)">보기</button></article>`}).join(''):'<p class="empty small-empty">아직 저장된 뽑기 결과가 없어요.</p>'}
const avatars=['🧑‍🚀','🧜‍♀️','🧜‍♂️','🐳','🦭','🐙','🦀','🐠'];let profileDraftAvatar=null;
function toggleProfileEditor(){const editor=$('#avatar-picker');editor.classList.toggle('hidden');if(!editor.classList.contains('hidden')){profileDraftAvatar=state.avatar||avatars[0];renderProfileEditor()}}
function renderProfileEditor(){const avatar=profileDraftAvatar||state.avatar||avatars[0];$('#nickname-input').value=state.nickname||'바다 구조대';$('#avatar-options').innerHTML=avatars.map(icon=>`<button type="button" class="avatar-option ${icon===avatar?'selected':''}" onclick="chooseAvatar('${icon}')">${icon}</button>`).join('')}
function chooseAvatar(avatar){profileDraftAvatar=avatar;renderProfileEditor()}
function saveProfile(){const nickname=$('#nickname-input').value.trim();state.nickname=nickname||'바다 구조대';state.avatar=profileDraftAvatar||avatars[0];saveState();renderMy();$('#avatar-picker').classList.add('hidden');toast('프로필을 저장했어요!')}
function marketOptions(f){return fish.filter(x=>x.name===f.name&&x.qty>0).sort((a,b)=>a.price-b.price)}
function openFish(id,drawDiscount=false){const i=typeof id==='number'?id:indexOfId(id),f=fishAt(i);if(!f)return;const offers=marketOptions(f),low=offers[0]?.price||f.price,high=offers[offers.length-1]?.price||f.price;$('#modal-content').innerHTML=`<div class="draw-result">${image(f,'result-photo')}<h2>${f.area} ${f.name}</h2><div class="market-box"><b>📊 ${f.name} 오늘의 시세</b><strong>${low.toLocaleString()} ~ ${high.toLocaleString()}원 <small>/ 1마리</small></strong><p>같은 어종 ${offers.length}개 판매자 상품을 비교했어요.</p></div><div class="seller-offers">${offers.map(o=>`<button type="button" class="seller-offer ${o.id===f.id?'selected':''}" onclick="openFish('${o.id}',${drawDiscount})"><span>${image(o,'offer-photo')}</span><b>${o.seller}</b><small>${o.area} · ${o.qty}마리</small><strong>${o.price.toLocaleString()}원</strong></button>`).join('')}</div><p>📍 ${f.area} 앞바다 · 오늘 ${f.time} 어획<br>남은 수량 <b>${f.qty}마리</b><br>추천 메뉴: ${f.recipes}</p><label class="quantity-label">구매 마리 수 <input id="buy-qty" type="number" min="1" max="${f.qty}" value="1" oninput="updatePurchaseTotal('${f.id}',${drawDiscount})"></label><div id="purchase-total" class="purchase-total"></div><label class="offer-label">적정 가격 제안 (1마리)<input id="price-offer" type="number" placeholder="원하는 가격 입력"><button type="button" onclick="submitOffer('${f.id}')">가격 제안하기</button></label><button type="button" class="primary purchase-button" onclick="reserve('${f.id}',${drawDiscount})">판매자와 픽업 확인하기</button></div>`;$('#modal').classList.remove('hidden');updatePurchaseTotal(f.id,drawDiscount)}
function updatePurchaseTotal(id,discount){const f=fish.find(x=>x.id===id),qty=Math.max(1,Math.min(f.qty,Number($('#buy-qty').value)||1));$('#buy-qty').value=qty;const unit=Math.round(f.price*(discount?.95:1)),total=unit*qty;$('#purchase-total').innerHTML=`${discount?'바다뽑기 5% 할인 적용 · ':''}<b>${qty}마리 · 총 ${total.toLocaleString()}원</b>`}
function submitOffer(id){const f=fish.find(x=>x.id===id),amount=Number($('#price-offer').value);if(!amount)return toast('제안할 가격을 입력해주세요.');state.offers=[...(state.offers||[]),{id,amount,date:new Date().toLocaleDateString('ko-KR')}];saveState();toast(`${f.name} ${amount.toLocaleString()}원 제안을 판매자에게 보냈어요!`)}
function closeModal(){$('#modal').classList.add('hidden')}
function reserve(id,discount){const f=fish.find(x=>x.id===id),qty=Math.max(1,Math.min(f.qty,Number($('#buy-qty').value)||1)),unit=Math.round(f.price*(discount?.95:1)),amount=unit*qty;if(!f.qty)return toast('준비된 수량이 모두 예약되었어요.');$('#modal-content').innerHTML=`<div class="draw-result"><div class="big">📍</div><h2>판매자와 픽업 확인</h2><p><b>${f.area} ${f.name} ${qty}마리</b> 예약 전, 판매자와 수령 정보를 확인해주세요.</p><div class="pickup-card"><b>📍 픽업 위치</b>${f.area} 수산물 직거래장<br>오늘 16:00 ~ 19:00 수령 가능<br><br><b>👨‍🌾 판매자 연락</b>${f.seller} · ${f.phone}<div class="contact-actions"><a href="tel:${f.phone.replaceAll('-','')}">📞 전화하기</a><a href="sms:${f.phone.replaceAll('-','')}">💬 문자 보내기</a></div></div><button type="button" class="primary purchase-button" onclick="showPayment('${id}',${qty},${amount})">픽업 확인 후 결제하기</button></div>`}
function showPayment(id,qty,amount){const f=fish.find(x=>x.id===id);$('#modal-content').innerHTML=`<div class="draw-result"><div class="big">💳</div><h2>가상 결제</h2><p><b>${f.area} ${f.name} ${qty}마리</b><br>결제 금액 <b>${amount.toLocaleString()}원</b></p><label class="payment-option"><input type="radio" name="pay" checked><span><b>카카오페이</b><small>테스트 결제 · 실제 청구되지 않아요</small></span></label><label class="payment-option"><input type="radio" name="pay"><span><b>신용·체크카드</b><small>테스트 결제 · 실제 청구되지 않아요</small></span></label><button type="button" class="primary purchase-button" onclick="completePayment('${id}',${qty},${amount})">${amount.toLocaleString()}원 결제하기</button></div>`}
function completePayment(id,qty,amount){const f=fish.find(x=>x.id===id);f.qty-=qty;const custom=(state.sellerFish||[]).find(x=>x.id===id);if(custom)custom.qty=f.qty;state.stock=state.stock||{};state.stock[id]=f.qty;if(f.qty<=0){state.soldOut=state.soldOut||{};state.soldOut[id]=today}state.rescued=(state.rescued||0)+qty;state.found=[...new Set([...(state.found||[]),f.name])];state.purchases=[{id:crypto.randomUUID?.()||Date.now().toString(),name:f.name,area:f.area,seller:f.seller,qty,amount,date:new Date().toLocaleDateString('ko-KR'),image:f.image},...(state.purchases||[])];saveState();render();$('#modal-content').innerHTML=`<div class="draw-result"><div class="big">🎉</div><h2>결제가 완료됐어요!</h2><p><b>${f.area} ${f.name} ${qty}마리</b> 구조에 참여해주셔서 감사합니다.<br>MY 화면의 구매 내역과 도감에서 확인할 수 있어요.</p><button class="primary" onclick="closeModal()">확인</button></div>`}
function renderRescue(){$('#rescue-list').innerHTML=[...available()].sort((a,b)=>b.qty-a.qty).map(f=>`<article class="rescue"><div class="rescue-head"><b>${f.emoji} ${f.area} ${f.name}</b><strong>${f.qty}마리 남음</strong></div><p>${f.seller} 판매 상품 · ${f.price.toLocaleString()}원/마리</p><div class="progress"><i style="width:${Math.min(100,(1-f.qty/31)*100)}%"></i></div><button onclick="openFish('${f.id}')">${f.name} 시세 보고 구조하기</button></article>`).join('')||'<p class="empty">이번 달 구조 요청이 없어요.</p>'}
function renderPurchaseHistory(all=false){const target=$('#purchase-history'),items=state.purchases||[];target.innerHTML=items.length?items.slice(0,all?items.length:2).map(p=>`<article class="history-item"><span>${p.image?`<img src="${p.image}" alt="${p.name}">`:'🐟'}</span><div><b>${p.name} ${p.qty}마리</b><small>${p.area} · ${p.seller} · ${p.date}</small></div><strong>${p.amount.toLocaleString()}원</strong></article>`).join(''):'<p class="empty small-empty">아직 구매 내역이 없어요.<br>바다 친구를 구조해보세요!</p>'}
function renderMy(){const rescued=state.rescued||0,found=state.found||[],dexLevels=state.dexLevels||{},avatar=state.avatar||avatars[0],nickname=state.nickname||'바다 구조대',growth=levelInfo(rescued),level=growth.level,titles=[[50,'👑 바다의 수호신'],[40,'🏆 부산 바다 전설'],[30,'🔱 심해 수호자'],[20,'🌊 푸른바다 지킴이'],[10,'⚓ 파도 탐험가'],[1,'🌱 새내기 구조대원']],title=titles.find(([min])=>level>=min)[1],benefits=[[50,'🎟️','픽업 10% 할인 쿠폰'],[120,'🧊','보냉백 교환'],[300,'🌊','바다 플로팅 키링'],[600,'👑','한정 수호자 배지']],maxDex=Math.max(0,...Object.values(dexLevels)),missions=[['draw','🎣','첫 바다뽑기',(state.drawHistory||[]).length,1,10],['dex','📖','도감 Lv.3 달성',maxDex,3,30],['title','⚓','칭호 파도 탐험가',level,10,80],['rescue','🛟','수산물 10마리 구조',rescued,10,50]],claimed=state.claimedMissions||[],mileage=state.mileage||0;$('#user-avatar').textContent=avatar;$('#user-nickname').textContent=nickname;$('#rescued-count').textContent=rescued;$('#found-count').textContent=found.length;$('#mileage-count').textContent=mileage;$('#level').textContent=level;$('#rescue-title').textContent=title;$('#level-copy').textContent=`구조 ${rescued}마리 · 다음 레벨까지 ${growth.toNext}마리 남았어요.`;$('#level-gauge-fill').style.width=`${growth.pct}%`;$('#level-gauge-copy').textContent=`${growth.progress} / ${growth.need}마리 · 다음 레벨까지 ${growth.toNext}마리`;$('#mission-list').innerHTML=missions.map(([key,icon,label,value,target,reward])=>{const done=value>=target,received=claimed.includes(key),pct=Math.min(100,value/target*100);return `<div class="mission ${done?'done':''}"><i>${icon}</i><span><b>${label}</b><small>${received?'마일리지 수령 완료':done?`완료 · ${reward}M 받기`:'진행 '+Math.min(value,target)+' / '+target}</small><em><u style="width:${pct}%"></u></em></span>${done?(received?'<strong>✓</strong>':`<button type="button" onclick="claimMission('${key}',${reward})">${reward}M 받기</button>`):''}</div>`}).join('');$('#reward-list').innerHTML=benefits.map(([cost,icon,title])=>`<div class="reward-row ${mileage>=cost?'unlocked':''}"><i>${icon}</i><span><b>${cost}M · ${title}</b><small>${mileage>=cost?'교환 가능!':'앞으로 '+Math.max(0,cost-mileage)+'M 더 모아요'}</small></span></div>`).join('');$('#dex-progress').textContent=`${found.length} / ${new Set(fish.map(f=>f.name)).size}`;$('#collection').innerHTML=[...new Map(fish.map(f=>[f.name,f])).values()].map(f=>`<div class="dex-card ${found.includes(f.name)?'found':''}"><span>${found.includes(f.name)?image(f):'?'}</span><b>${found.includes(f.name)?f.name:'???'}</b><small>${found.includes(f.name)?`도감 Lv.${dexLevels[f.name]||1}`:'미발견 생물'}</small></div>`).join('');renderPurchaseHistory()}
let userLocation=null,userLocationMarker=null,sellerMarkersLayer=null,selectedMapArea='';
function safeText(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function distanceKm(from,to){const radius=6371,toRad=value=>value*Math.PI/180,dLat=toRad(to.lat-from.lat),dLng=toRad(to.lng-from.lng),a=Math.sin(dLat/2)**2+Math.cos(toRad(from.lat))*Math.cos(toRad(to.lat))*Math.sin(dLng/2)**2;return radius*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function formatMinutes(minutes){const rounded=Math.max(5,Math.round(minutes/5)*5);return rounded<60?`${rounded}분`:`${Math.floor(rounded/60)}시간${rounded%60?` ${rounded%60}분`:''}`}
function travelEstimate(point){if(!userLocation)return null;const directKm=distanceKm(userLocation,point),estimatedMinutes=(directKm*1.25/32)*60+5;return{directKm,time:formatMinutes(estimatedMinutes),label:`차량 약 ${formatMinutes(estimatedMinutes)} · 직선 ${directKm.toFixed(1)}km`}}
function sellerGroupsForArea(area){const groups=new Map;available().filter(f=>f.area===area).forEach(f=>{const key=`${f.area}|${f.seller}`,current=groups.get(key)||{area:f.area,seller:f.seller,fish:[],qty:0};current.fish.push(f.name);current.qty+=f.qty;groups.set(key,current)});return[...groups.values()].map(group=>({...group,fish:[...new Set(group.fish)]}))}
function renderCatchPointGuide(){const target=$('#catch-point-guide');if(!target)return;target.innerHTML=Object.entries(SEA_POINTS).map(([area,point])=>`<button type="button" class="catch-guide-card" onclick="focusArea('${area}')"><span>${area==='기장'?'🐟':area==='송정'?'🐠':area==='영도'?'⚓':'🌅'}</span><div><b>${safeText(point.label)}</b><p>${safeText(point.description)}</p><small>주요 어종 · ${safeText(point.specialty)}</small></div><em>지도에서 보기 ›</em></button>`).join('')}
function renderTravelList(){const target=$('#travel-list');if(!target)return;target.innerHTML=Object.entries(SEA_POINTS).map(([area,point])=>{const travel=travelEstimate(point),sellers=sellerGroupsForArea(area);return`<button type="button" class="travel-card ${travel?'':'no-location'}" onclick="focusArea('${area}')"><b>🌊 ${area} 앞바다</b><small>${safeText(point.label)} · 판매자 ${sellers.length}곳</small><strong>${travel?safeText(travel.label):'GPS 위치 확인 후 시간 표시'}</strong></button>`}).join('')}
function filterArea(area){selectedMapArea=area;const point=SEA_POINTS[area],choices=available().filter(f=>f.area===area),travel=travelEstimate(point),sellers=sellerGroupsForArea(area);$('#area-result').innerHTML=`<div class="area-result-head"><b>📍 ${safeText(point.label)} · 오늘 입고</b><strong>${travel?safeText(travel.label):'GPS 위치 필요'}</strong></div><p class="area-catch-list">${choices.map(f=>`${f.emoji} ${safeText(f.name)} · ${f.qty}마리`).join('<br>')||'오늘 등록된 수산물이 없어요.'}</p><div class="seller-arrivals">${sellers.map(seller=>`<div class="seller-arrival"><span><b>◆ ${safeText(seller.seller)}</b><small>${safeText(point.label)} 판매 · ${seller.fish.map(safeText).join(', ')}</small></span><strong>${travel?`차량 약 ${safeText(travel.time)}`:'시간 확인 대기'}</strong></div>`).join('')||'<small>현재 등록된 판매자가 없어요.</small>'}</div>`}
function focusArea(area){const point=SEA_POINTS[area];if(busanMap)busanMap.setView([point.lat,point.lng],13,{animate:true});filterArea(area)}
function requestUserLocation(){const button=$('#locate-button'),status=$('#location-status');if(!navigator.geolocation){status.textContent='이 기기에서는 GPS 위치를 사용할 수 없어요.';return}button.disabled=true;button.textContent='위치 확인 중…';status.textContent='기기의 현재 위치를 확인하고 있어요.';navigator.geolocation.getCurrentPosition(position=>{userLocation={lat:position.coords.latitude,lng:position.coords.longitude};if(busanMap){if(userLocationMarker)busanMap.removeLayer(userLocationMarker);const icon=L.divIcon({className:'',html:'<div class="user-location-pulse" aria-label="내 현재 위치"></div>',iconSize:[20,20],iconAnchor:[10,10]});userLocationMarker=L.marker([userLocation.lat,userLocation.lng],{icon,zIndexOffset:1000}).addTo(busanMap).bindPopup('<b>📍 내 현재 위치</b><br>거리 계산의 출발점이에요.');const busanCenter={lat:35.145,lng:129.09},nearBusan=distanceKm(userLocation,busanCenter)<55;status.textContent=nearBusan?'현재 위치를 지도에 표시하고 이동시간을 계산했어요.':'현재 위치가 부산 지도 밖이라 거리와 시간만 계산했어요.'}else status.textContent='현재 위치를 확인했어요. 지도를 여는 중이에요.';renderTravelList();if(selectedMapArea)filterArea(selectedMapArea);renderSellerMarkers();button.disabled=false;button.textContent='✓ 위치 새로고침'},error=>{const messages={1:'위치 권한이 꺼져 있어요. 브라우저에서 위치를 허용해 주세요.',2:'현재 위치를 확인할 수 없어요. 잠시 후 다시 시도해 주세요.',3:'위치 확인 시간이 초과됐어요. 다시 눌러 주세요.'};status.textContent=messages[error.code]||'위치 확인 중 문제가 생겼어요.';button.disabled=false;button.textContent='📍 GPS 다시 시도'},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
function readImage(file){return new Promise(resolve=>{if(!file)return resolve('');const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file)})}
$('#seller-form').addEventListener('submit',async e=>{e.preventDefault();const name=$('#new-name').value.trim(),area=$('#new-area').value,qty=Number($('#new-qty').value),image=await readImage($('#new-photo').files[0]);const product={id:`seller-${Date.now()}`,name,area,time:$('#new-time').value,price:Number($('#new-price').value),qty,emoji:'🐟',recipes:'구이 · 회 · 조림',image:image||photo[name]||'',phone:$('#seller-phone').value.trim()||'010-2458-7721',seller:$('#seller-name').value.trim(),months:[selectedMonth],sellerPhoto:!!image};state.sellerFish=[product,...(state.sellerFish||[])];saveState();hydrate();e.target.reset();go('home');render();if(busanMap){renderSellerMarkers();renderTravelList()}toast(`${name} ${qty}마리가 ${name} 카테고리에 등록됐어요!`)});
function render(){const current=available(),total=current.reduce((a,f)=>a+f.qty,0),areas=['기장','송정','영도','다대포'];$('#total-count').textContent=total;$('#season-insight').innerHTML=`오늘 입고된 부산 4개 권역의 <b>${current.length}개 판매 상품</b>을 만나보세요.`;const urgent=[...current].sort((a,b)=>b.qty-a.qty)[0];$('#urgent-card').innerHTML=urgent?`<div class="urgent-top"><span>🚨 바다 구조 요청!</span><span>${urgent.qty}마리 남음</span></div><b>${urgent.area} ${urgent.name}</b><p>${urgent.seller}의 오늘 입고 상품이에요.<br>시세를 비교하고 적정 가격을 제안해보세요!</p><div class="progress"><i style="width:${Math.min(100,(1-urgent.qty/31)*100)}%"></i></div><small>구조 진행 중</small>`:'<b>오늘 등록된 어종이 없어요.</b>';$('#fish-list').innerHTML=areas.map(area=>{const items=current.filter(f=>f.area===area);return `<section class="region-block"><div class="region-head"><h3>📍 ${area} 앞바다</h3><small>${items.length}개 상품 입고</small></div><div class="region-fish-grid">${items.map(f=>{const options=marketOptions(f),low=options[0]?.price||f.price,soldOut=f.qty<=0;return `<article class="fish ${soldOut?'sold-out':''}" onclick="handleFishClick('${f.id}')"><div class="fish-photo">${image(f)}${soldOut?'<span class="sold-tag">SOLD OUT</span>':''}</div><b>${f.name}</b><small>${f.seller}${f.sellerPhoto?' · 판매자 사진':''}</small><small>${soldOut?'오늘 판매 완료 · 내일 삭제':`${f.time} 어획 · ${f.qty}마리`}</small><strong>${low.toLocaleString()}원~</strong><em>${soldOut?'● 매진':'📊 '+options.length+'곳 시세 비교'}</em></article>`}).join('')||'<p class="empty">오늘 등록된 수산물이 없어요.</p>'}</div></section>`}).join('')}
let busanMap;
function refreshBusanMap(){if(!busanMap)return;requestAnimationFrame(()=>busanMap.invalidateSize({pan:false}))}
function renderSellerMarkers(){if(!busanMap)return;if(!sellerMarkersLayer)sellerMarkersLayer=L.layerGroup().addTo(busanMap);sellerMarkersLayer.clearLayers();Object.entries(SEA_POINTS).forEach(([area,point])=>{sellerGroupsForArea(area).forEach((seller,index)=>{const angle=index*Math.PI*2/Math.max(1,sellerGroupsForArea(area).length),lat=point.lat+0.0045*Math.cos(angle),lng=point.lng+0.0055*Math.sin(angle),travel=travelEstimate(point),marker=L.circleMarker([lat,lng],{radius:7,color:'#fff',weight:2,fillColor:'#176c9b',fillOpacity:1}).addTo(sellerMarkersLayer);marker.bindTooltip(`◆ ${safeText(seller.seller)}`,{direction:'top',offset:[0,-8],className:'seller-tooltip'});marker.on('click',()=>{filterArea(area);marker.bindPopup(`<b>◆ ${safeText(seller.seller)}</b><br>${safeText(point.label)} 판매 위치<br>${seller.fish.map(safeText).join(', ')}${travel?`<br><strong>${safeText(travel.label)}</strong>`:''}`).openPopup()})})})}
function initBusanMap(){if(!window.L)return;if(busanMap){renderSellerMarkers();renderCatchPointGuide();renderTravelList();refreshBusanMap();return}const isTouchDevice=window.matchMedia('(pointer:coarse)').matches,busanBounds=L.latLngBounds([34.98,128.91],[35.31,129.27]);busanMap=L.map('busan-real-map',{zoomControl:false,scrollWheelZoom:false,dragging:!isTouchDevice,touchZoom:false,doubleClickZoom:!isTouchDevice,boxZoom:!isTouchDevice,keyboard:!isTouchDevice,tap:false,minZoom:10,maxBounds:busanBounds,maxBoundsViscosity:1}).setView([35.145,129.10],11);L.control.zoom({position:'bottomright'}).addTo(busanMap);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenStreetMap contributors'}).addTo(busanMap);window.addEventListener('resize',refreshBusanMap,{passive:true});Object.entries(SEA_POINTS).forEach(([area,point])=>{const marker=L.circleMarker([point.lat,point.lng],{radius:9,color:'#fff',weight:3,fillColor:'#ef6755',fillOpacity:1}).addTo(busanMap),eastPoint=area==='기장'||area==='송정',direction=eastPoint?'left':area==='다대포'?'right':'top',offset=eastPoint?[-16,0]:area==='다대포'?[22,0]:[0,-11],labelClass=`catch-point-label${area==='다대포'?' catch-dadaepo':''}`;marker.bindTooltip(`<b>${safeText(point.label)}</b><small>${safeText(area)} 어획 포인트</small>`,{permanent:true,direction,offset,className:labelClass});marker.on('click',()=>{filterArea(area);const items=available().filter(f=>f.area===area),travel=travelEstimate(point);marker.bindPopup(`<b>📍 ${safeText(point.label)}</b><br>${safeText(point.description)}<br><br>${items.map(f=>`${f.emoji} ${safeText(f.name)} · ${f.qty}마리`).join('<br>')||'오늘 등록된 수산물이 없어요.'}${travel?`<br><strong>${safeText(travel.label)}</strong>`:''}`).openPopup()})});renderSellerMarkers();renderCatchPointGuide();renderTravelList();refreshBusanMap()}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}
render();renderMy();
